package com.example.sender

import android.content.Intent
import android.os.Bundle
import android.widget.Button
import android.widget.EditText
import androidx.appcompat.app.AppCompatActivity
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.ktx.auth
import com.google.firebase.database.DatabaseReference
import com.google.firebase.database.FirebaseDatabase
import com.google.firebase.ktx.Firebase

class OrderCreationActivity : AppCompatActivity() {

    private lateinit var receiverName: EditText
    private lateinit var idNo: EditText
    private lateinit var phoneNumber: EditText
    private lateinit var emailAddress: EditText
    private lateinit var countryCityTown: EditText
    private lateinit var createButton: Button
    // Creating a variable for our Firebase Database.
    private var firebaseDatabase: FirebaseDatabase? = null

    // Creating a variable for our Database Reference for Firebase.
    private var databaseReference: DatabaseReference? = null

    private lateinit var auth: FirebaseAuth


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_order_creation2)

        // Initialize Firebase Database
        firebaseDatabase = FirebaseDatabase.getInstance()

        // Initialize Firebase Authentication
        auth = Firebase.auth

        // Get the current user's ID from Firebase Authentication
        val user = auth.currentUser
        val userId = user?.uid
            ?: // Handle the case where the user is not logged in

            return

        // Reference to "orders" node under the user's node
        databaseReference = firebaseDatabase?.getReference("orders")?.child(userId)


        receiverName = findViewById(R.id.nameEditText)
        idNo = findViewById(R.id.editText14)
        phoneNumber = findViewById(R.id.editText15)
        emailAddress = findViewById(R.id.editText16)
        countryCityTown = findViewById(R.id.editText17)
        createButton = findViewById(R.id.createButton)

        createButton.setOnClickListener {
            // Get input values
            val name = receiverName.text.toString()
            val id = idNo.text.toString()
            val phone = phoneNumber.text.toString()
            val email = emailAddress.text.toString()
            val location = countryCityTown.text.toString()

            // Create an Order object to store the data
            val order = Order(name, id, phone, email, location)

            // Push the order data to Firebase
            databaseReference?.push()?.setValue(order.toMap()) // Use the toMap() function here

            // Clear the input fields
            receiverName.text.clear()
            idNo.text.clear()
            phoneNumber.text.clear()
            emailAddress.text.clear()
            countryCityTown.text.clear()

            // Create an Intent to navigate to ContentOrderCreationActivity
            val intent = Intent(this@OrderCreationActivity, ContentOrderCreationActivity::class.java)
            startActivity(intent)
        }
    }
}

data class Order(
    val receiverName: String = "",
    val idNo: String = "",
    val phoneNumber: String = "",
    val emailAddress: String = "",
    val countryCityTown: String = "",
    val parcelId: String = generateParcelId(), // Autogenerated parcelId
    var key: String? = null // Add this line to declare the key property
) {
    companion object {
        private fun generateParcelId(): String {
            // You can use a unique identifier generator or timestamp
            return "PARCEL_${System.currentTimeMillis()}"
        }
    }

    // Using map function for easy serialization and deserialization from database
    fun toMap(): Map<String, Any?> {
        return mapOf(
            "receiverName" to receiverName,
            "idNo" to idNo,
            "phoneNumber" to phoneNumber,
            "emailAddress" to emailAddress,
            "countryCityTown" to countryCityTown,
            "parcelId" to parcelId
        )
    }
}

